# Generated by Django 4.0.4 on 2022-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_dream_alter_profile_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('mind', 'マインド'), ('research', 'リサーチ'), ('order', '発注'), ('product_desctription', '商品説明'), ('product_image', '商品画像'), ('outsourcing', '外注'), ('tool', 'ツール'), ('battle', '商戦'), ('other', 'その他')], max_length=100, verbose_name='タグ')),
                ('output', models.ManyToManyField(to='base.output')),
            ],
        ),
    ]
