# Generated by Django 4.0.4 on 2022-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_outputtagmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputtagmodel',
            name='output',
        ),
        migrations.AddField(
            model_name='output',
            name='tags',
            field=models.ManyToManyField(to='base.outputtagmodel'),
        ),
    ]
