# Generated by Django 4.0.4 on 2022-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_outputtagmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputtagmodel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='outputtagmodel',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='タグ'),
        ),
    ]
